name: xxscreeps

on:
  push:
    branches: [ main ]

jobs:
  build-test-release:
    name: Build, Test, Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      # Setup
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v6
        with:
          cache: true

      # Build & test
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run test --private-transform=isolated-vm

      # Publish to edge version to npm
      - run: (cd packages/xxscreeps; pnpm version prerelease --preid=$(git rev-parse --short HEAD) --no-git-tag-version)
      - id: publish
        shell: sh
        run: pnpm publish --filter '!@xxscreeps/pathfinder' --no-git-checks --provenance --recursive --tag edge
